// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zl1_l4suUzaN91KNgVakuTd4kOl1AQM',
    appId: '1:658897248078:web:719078048f5878412c881f',
    messagingSenderId: '658897248078',
    projectId: 'crowdfans-prod',
    authDomain: 'crowdfans-prod.firebaseapp.com',
    storageBucket: 'crowdfans-prod.firebasestorage.app',
    measurementId: 'G-F1W46DEHJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVb1P74NVjXfxAY4aIpE1WkMeYdxiWm9s',
    appId: '1:658897248078:android:edd3c987eb54bcdc2c881f',
    messagingSenderId: '658897248078',
    projectId: 'crowdfans-prod',
    storageBucket: 'crowdfans-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyobj9XSkYjInCZoGZ8ecfQJYkzClB1DI',
    appId: '1:658897248078:ios:874725d168494cab2c881f',
    messagingSenderId: '658897248078',
    projectId: 'crowdfans-prod',
    storageBucket: 'crowdfans-prod.firebasestorage.app',
    iosBundleId: 'com.crowdfans.crowdfans',
  );
}
